### ISSUE TITLE
Unable to login to machine

### ISSUE THREAD

**Issue by BenjaminDR** [peno-cw-2018/ertvelde#1]
When I try to logon to the machine with my r-number and password the server responds with
`Permission denied, please try again.`

Is there another account I am supposed to be using or are the accounts not yet properly configured?

Thank you in advance,
Benjamin De Roeck | CTO Team Phoenix

**Comment by ghost** [comment]
We, group 8, are writing a little "[How to](https://docs.google.com/document/d/1H4yv0NrwwLIi4mAbm_FTKOHI2iQFY7m5XRBu9ug3exw/edit?usp=sharing)", pleas feel free to adjust or correct any mistakes

**Comment by btj** [comment]
This was a bug in the machine's configuration; it should now be fixed.

Note that you can log in to `ertvelde` simply using your `r` number and your password. You can also log in using your `r` number and any SSH key listed in your `.ssh/authorized_keys` file in your departmental home directory. One way to add a key to that file is by generating it through [this site](https://www.cs.kuleuven.be/restricted/ssh/).

Note that you cannot access `ertvelde` directly from outside the KU Leuven network. If you are outside the KU Leuven network, you first have to log in to `st.cs.kuleuven.be` using SSH, and then, from that machine, log in to `ertvelde` (or create a tunnel). To log in to `st.cs.kuleuven.be`, you need to use an SSH key listed in your `.ssh/authorized_keys` file in your departmental home directory; you cannot log in to that machine using your password.
